name: Oil Offers Ingestion

on:
  schedule:
    # - cron: "0 21 * * *"
  workflow_dispatch: {}

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingestion
        env:
          ORIGIN_URL: ${{ secrets.ORIGIN_URL }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          OFFERS_TABLE_NAME: ${{ vars.OFFERS_TABLE_NAME }}
        run: |
          python ingest.py
