name: Update README status

on:
  schedule:
    # - cron: '* 21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build README status
        env:
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          SUPABASE_DB_NAME: ${{ secrets.SUPABASE_DB_NAME }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          OFFERS_TABLE_NAME: ${{ vars.OFFERS_TABLE_NAME }}
        run: python update_readme.py

      - name: Commit README if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update README status [skip ci]'
          file_pattern: README.md
